In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import UpROOT.io as io
import UpROOT.config as conf
import UpROOT.io as io

In [3]:
io.list_dataset_trees(
    dataset="b2hhh"
)

Archivo: B2HHH_MagnetUp.root
Árboles encontrados (1):
1. DecayTree

Archivo: B2HHH_MagnetDown.root
Árboles encontrados (1):
1. DecayTree

{PosixPath('/home/karna/Documentos/PF/data/B2HHH_MagnetUp.root'): ['DecayTree'],
 PosixPath('/home/karna/Documentos/PF/data/B2HHH_MagnetDown.root'): ['DecayTree']}

In [4]:
io.list_branches(
    dataset='b2hhh',
    show_trees=True,
    show_branches=True,
    txt_path="b2hhh",
)

Árboles encontrados (1):
1. DecayTree
Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Ramas encontradas: 26
 - B_FlightDistance
 - B_VertexChi2
 - H1_Charge
 - H1_IPChi2
 - H1_PX
 - H1_PY
 - H1_PZ
 - H1_ProbK
 - H1_ProbPi
 - H1_isMuon
 - H2_Charge
 - H2_IPChi2
 - H2_PX
 - H2_PY
 - H2_PZ
 - H2_ProbK
 - H2_ProbPi
 - H2_isMuon
 - H3_Charge
 - H3_IPChi2
 - H3_PX
 - H3_PY
 - H3_PZ
 - H3_ProbK
 - H3_ProbPi
 - H3_isMuon
Lista de ramas guardada en: /home/karna/Documentos/PF/MadGraph/assset/txt/branches/b2hhh.txt

['B_FlightDistance',
 'B_VertexChi2',
 'H1_Charge',
 'H1_IPChi2',
 'H1_PX',
 'H1_PY',
 'H1_PZ',
 'H1_ProbK',
 'H1_ProbPi',
 'H1_isMuon',
 'H2_Charge',
 'H2_IPChi2',
 'H2_PX',
 'H2_PY',
 'H2_PZ',
 'H2_ProbK',
 'H2_ProbPi',
 'H2_isMuon',
 'H3_Charge',
 'H3_IPChi2',
 'H3_PX',
 'H3_PY',
 'H3_PZ',
 'H3_ProbK',
 'H3_ProbPi',
 'H3_isMuon']

In [5]:
io.load_dataframe(
    branches=None,
    dataset='b2hhh'
).head()

Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 8,556,118 eventos

,B_FlightDistance,B_VertexChi2,H1_PX,H1_PY,H1_PZ,H1_ProbK,H1_ProbPi,H1_Charge,H1_IPChi2,H1_isMuon,...,H2_IPChi2,H2_isMuon,H3_PX,H3_PY,H3_PZ,H3_ProbK,H3_ProbPi,H3_Charge,H3_IPChi2,H3_isMuon
0,11.241923,3.870827,1038.634354,4933.332660,164858.932313,0.012529,0.022087,1,16.937403,0,...,10.985674,0,-1946.910223,39.196412,29045.997481,0.009646,0.893131,-1,492.019550,0
1,14.429881,10.294972,-318.157696,-6407.683029,152900.152771,0.066721,0.685733,1,21.398055,0,...,351.338309,0,-1151.694873,-2406.638825,33660.348215,0.946793,0.068788,-1,587.399033,0
2,12.489381,9.303937,-97.802248,199.043666,4381.611081,0.063709,0.867898,1,1.154180,0,...,828.728775,0,627.983171,6277.041303,163852.187436,0.096775,0.534711,-1,3.511918,0
3,9.420983,4.829225,-527.819868,-651.630894,5063.986480,0.006649,0.995989,-1,1559.846172,0,...,3.262061,0,-2269.719699,-3665.766947,107937.151828,0.073778,0.096622,1,6.836508,1
4,7.362626,5.922298,-61.928986,552.828398,27007.961659,0.004962,0.211233,-1,8.178476,0,...,495.128111,0,-3236.872273,-94.994283,145404.605206,0.138766,0.709732,1,2.682517,0

In [6]:
io.load_dataframe(
    branches=io.txt_data("b2hhh"),
    dataset='b2hhh'
).head()

Ramas cargadas desde: /home/karna/Documentos/PF/MadGraph/analysis/b2hhh.txt
Cantidad de ramas: 21
Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 8,556,118 eventos

,H1_PX,H1_PY,H1_PZ,H1_ProbK,H1_ProbPi,H1_Charge,H1_isMuon,H2_PX,H2_PY,H2_PZ,...,H2_ProbPi,H2_Charge,H2_isMuon,H3_PX,H3_PY,H3_PZ,H3_ProbK,H3_ProbPi,H3_Charge,H3_isMuon
0,1038.634354,4933.332660,164858.932313,0.012529,0.022087,1,0,248.779834,248.630719,16906.431769,...,0.878307,-1,0,-1946.910223,39.196412,29045.997481,0.009646,0.893131,-1,0
1,-318.157696,-6407.683029,152900.152771,0.066721,0.685733,1,0,382.380373,114.052010,6374.152504,...,0.906743,-1,0,-1151.694873,-2406.638825,33660.348215,0.946793,0.068788,-1,0
2,-97.802248,199.043666,4381.611081,0.063709,0.867898,1,0,208.034060,462.606163,3814.362281,...,0.970704,-1,0,627.983171,6277.041303,163852.187436,0.096775,0.534711,-1,0
3,-527.819868,-651.630894,5063.986480,0.006649,0.995989,-1,0,80.115036,-68.143638,2111.592278,...,0.772366,1,0,-2269.719699,-3665.766947,107937.151828,0.073778,0.096622,1,1
4,-61.928986,552.828398,27007.961659,0.004962,0.211233,-1,0,-787.337582,-1503.071145,15912.287168,...,0.455540,1,0,-3236.872273,-94.994283,145404.605206,0.138766,0.709732,1,0

In [7]:
p_KKK = (
    '(H1_ProbK > 0.5) & (H2_ProbK > 0.5) & (H3_ProbK > 0.5) & '
    '(H1_ProbPi < 0.5) & (H2_ProbPi < 0.5) & (H3_ProbPi < 0.5) & '
    '(H1_isMuon == 0) & (H2_isMuon == 0) & (H3_isMuon == 0)'
)
io.load_dataframe(
    branches=None,
    cut=p_KKK,
    dataset='b2hhh'
).head()

Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 23,895 eventos

,B_FlightDistance,B_VertexChi2,H1_PX,H1_PY,H1_PZ,H1_ProbK,H1_ProbPi,H1_Charge,H1_IPChi2,H1_isMuon,...,H2_IPChi2,H2_isMuon,H3_PX,H3_PY,H3_PZ,H3_ProbK,H3_ProbPi,H3_Charge,H3_IPChi2,H3_isMuon
325,10.428140,4.056947,-4168.055539,-704.953919,24548.766576,0.771199,0.051726,-1,1002.657075,0,...,714.174519,0,-8864.962492,-7428.640292,77446.175923,0.934580,0.128720,1,536.585115,0
539,33.591307,2.220242,1295.910334,-61.956920,35569.606902,0.932006,0.058690,-1,6672.092707,0,...,737.219732,0,-341.750434,3317.423370,24380.200353,0.968883,0.129317,1,23332.453390,0
588,16.531858,11.593388,1493.048615,1944.600925,33003.915368,0.953512,0.104768,-1,1731.923563,0,...,499.998835,0,4779.029220,-287.829864,53908.496894,0.844950,0.064803,1,3484.193030,0
1086,4.102797,11.321708,-236.694032,843.809179,28207.109021,0.655129,0.045339,-1,5.033764,0,...,6.588705,0,-1085.332141,-3076.759324,30036.196827,0.912293,0.080841,1,489.046805,0
1236,3.509346,5.739399,123.873807,856.290459,51956.566616,0.940484,0.078221,-1,7.005894,0,...,2.090424,0,1639.997962,2660.275891,19441.349314,0.702135,0.028641,1,888.535134,0

In [8]:
io.csv(
    output_path="b2hhh",
    branches=None,
    dataset='b2hhh'
)

Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 8,556,118 eventos
CSV guardado en: /home/karna/Documentos/PF/MadGraph/assset/txt/csv/b2hhh.csv
Filas: 8,556,118    |    Columnas: 26

PosixPath('/home/karna/Documentos/PF/MadGraph/assset/txt/csv/b2hhh.csv')

In [9]:
io.csv(
    output_path="b2hhh_cut",
    branches=None,
    dataset='b2hhh',
    cut=p_KKK
)

Archivo: B2HHH_MagnetUp.root
Árbol seleccionado: DecayTree
Archivo: B2HHH_MagnetDown.root
Árbol seleccionado: DecayTree
Total de eventos: 23,895 eventos
CSV guardado en: /home/karna/Documentos/PF/MadGraph/assset/txt/csv/b2hhh_cut.csv
Filas: 23,895    |    Columnas: 26

PosixPath('/home/karna/Documentos/PF/MadGraph/assset/txt/csv/b2hhh_cut.csv')